apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: kind-lab
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/atwin140/Kind-lab.git
  ref:
    branch: traefik-lab
