apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nginx
configMapGenerator:
- name: nginx-html
  files:
  - index.html=./index.html
- name: nginx-css
  files:
  - style.css=./style.css
resources:
- namespace.yaml
- deployment.yaml
- service.yaml

# - ingress.yaml
